### ISSUE TITLE
NZBGet Autolaunch

### ISSUE THREAD

**Issue by rprice2021** [DyonR/docker-nzbgetvpn#1]
Hi,
Installed the container on Synology 918+ (DSM 6.2.3) and it launches and connects to OpenVPN correctly with the environment variables set as per the readme.
NZBGet is not launched automatically.  I must connect a bash session and start the daemon manually using the start.sh script or nzbget -D.  NZBGet then runs as expected.
Is this normal behaviour?

The container is running only 3 processes before I launch NZBGet manually:
iptables.sh
openvpn
sleep 1

**Comment by DyonR** [comment]
Should not be normal, could you maybe post the log of the Docker Container? Make sure to remove any sensitive info

**Comment by rprice2021** [comment]
This is all that is in the Synology Docker GUI after I start the container:

2021-05-18 09:52:29
stdout
Tue May 18 09:52:29 2021 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
2021-05-18 09:52:29
stdout
Tue May 18 09:52:29 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.725379 [INFO] Starting OpenVPN...
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.654805 [INFO] Adding 1.0.0.1 to resolv.conf
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.575072 [INFO] Adding 1.1.1.1 to resolv.conf
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.513611 [INFO] VPN_OPTIONS not defined (via -e VPN_OPTIONS)
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.453617 [INFO] NAME_SERVERS defined as '1.1.1.1,1.0.0.1'
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.373697 [INFO] LAN_NETWORK defined as '192.168.10.0/24'
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.292639 [INFO] VPN_DEVICE_TYPE defined as 'tun0'
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.232539 [INFO] VPN_PROTOCOL defined as 'tcp-client'
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.171937 [INFO] VPN_PORT defined as '80'
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.110200 [INFO] VPN_REMOTE defined as ‘xxxxxxxx’
2021-05-18 09:52:28
stdout
2021-05-18 09:52:28.048242 [INFO] VPN remote line defined as ‘xxxxxxxxx 80'
2021-05-18 09:52:27
stdout
dos2unix: converting file /config/openvpn/xxxxxxxxxx.ovpn to Unix format...
2021-05-18 09:52:27
stdout
2021-05-18 09:52:27.810678 [INFO] OpenVPN config file is found at /config/openvpn/xxxxxxxxx.ovpn
2021-05-18 09:52:27
stdout
2021-05-18 09:52:27.545640 [INFO] VPN_TYPE defined as 'openvpn'
2021-05-18 09:52:27
stdout
2021-05-18 09:52:27.480776 [INFO] VPN_ENABLED defined as 'yes'
2021-05-18 09:51:31
stdout
Enter Auth Username:

**Comment by rprice2021** [comment]
The last line in the dockerfile launches a bash session and openvpn:
CMD ["/bin/bash", "/etc/openvpn/start.sh"]
I can't see where nzbget is called...?

**Comment by DyonR** [comment]
It seems like it has problems executing, or setting up, the OpenVPN connection. 
At line 266 of the start.sh it starts the script to launch nzbget. 
I don't get why it doesn't work for you. 
Because of this the VPN Connection is also probably not active if you launch it manually

**Comment by rprice2021** [comment]
OK.  I have solved the initial problem and created another:
My initial problem was because I had fat-fingered a leading space into the VPN_PASSWORD field. That didn't create an error but it left the bash session with the openvpn.init script hanging and waiting for input.
Now that I have corrected that the container launches OK, but I can't connect to the nzbget webui - the browser session just hangs.  

I have pasted the log file - there are a bunch of iptables errors?

Thanks for the help - and the container!

2021-05-19 11:14:04.835023 [INFO] Network is up
2021-05-19 11:14:04.552488 [INFO] Started NZBGet daemon successfully...
2021-05-19 11:14:04.454258 [INFO] NZBGet PID: 237
Logging to /config/NZBGet/logs/nzbget.log.
2021-05-19 11:14:03.320698 [INFO] Starting NZBGet daemon...
req: No value provided for Subject Attribute CN, skipped
req: No value provided for Subject Attribute OU, skipped
req: No value provided for Subject Attribute O, skipped
-----
writing new private key to '/config/NZBGet/WebUIKey.key'
.......................+++++
.............................+++++
Generating a RSA private key
2021-05-19 11:14:02.866895 [WARNING] WebUI Key is missing, generating a new Certificate and Key
Wed May 19 11:14:02 2021 Initialization Sequence Completed
Wed May 19 11:14:02 2021 /sbin/ip route add 10.10.128.1/32 via 10.10.128.5
Wed May 19 11:14:02 2021 /sbin/ip route add 128.0.0.0/1 via 10.10.128.5
Wed May 19 11:14:02 2021 /sbin/ip route add 0.0.0.0/1 via 10.10.128.5
Wed May 19 11:14:02 2021 /sbin/ip route add xxxxxxxxx/32 via 172.17.0.1
2021-05-19 11:14:02.755444 [INFO] ENABLE_SSL is set to yes
2021-05-19 11:14:02.454972 [INFO] UMASK defined as '002'
2021-05-19 11:14:02.378234 [INFO] An user with PUID 1032 already exists in /etc/passwd, nothing to do.
2021-05-19 11:14:02.315771 [INFO] A group with PGID 100 already exists in /etc/group, nothing to do.
2021-05-19 11:14:02.255268 [INFO] Python3 is already installed, nothing to do.
--------------------
iptables/1.8.2 Failed to initialize nft: Protocol not supported
--------------------
2021-05-19 11:14:02.156693 [INFO] iptables defined as follows...
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
2021-05-19 11:14:00.745838 [INFO] iptable_mangle support detected, adding fwmark for tables
x_tables               16302  23 ip6table_filter,xt_ipvs,xt_iprange,xt_mark,ip6table_mangle,xt_recent,ip_tables,xt_tcpudp,ipt_MASQUERADE,xt_geoip,xt_limit,xt_state,xt_conntrack,xt_LOG,xt_mac,xt_nat,xt_multiport,iptable_filter,xt_TCPMSS,xt_REDIRECT,iptable_mangle,ip6_tables,xt_addrtype
ip_tables              14092  3 iptable_filter,iptable_mangle,iptable_nat
iptable_mangle          1656  0
--------------------
192.168.10.0/24 via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2 
10.10.128.5 dev tun0 proto kernel scope link src 10.10.128.6 
10.8.0.0/29 via 172.17.0.1 dev eth0 
default via 172.17.0.1 dev eth0 
--------------------
2021-05-19 11:14:00.649151 [INFO] ip route defined as follows...
2021-05-19 11:14:00.577925 [INFO] Adding 10.8.0.0/29 as route via docker eth0
2021-05-19 11:14:00.497333 [INFO] Adding 192.168.10.0/24 as route via docker eth0
2021-05-19 11:14:00.409973 [INFO] Docker network defined as 172.17.0.0/16
Wed May 19 11:13:59 2021 /sbin/ip addr add dev tun0 local 10.10.128.6 peer 10.10.128.5
Wed May 19 11:13:57 2021 /sbin/ip link set dev tun0 up mtu 1500
Wed May 19 11:13:57 2021 TUN/TAP TX queue length set to 100
Wed May 19 11:13:57 2021 TUN/TAP device tun0 opened
Wed May 19 11:13:57 2021 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Wed May 19 11:13:57 2021 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Wed May 19 11:13:57 2021 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Wed May 19 11:13:57 2021 Data Channel: using negotiated cipher 'AES-128-GCM'
Wed May 19 11:13:57 2021 OPTIONS IMPORT: data channel crypto options modified
Wed May 19 11:13:57 2021 OPTIONS IMPORT: adjusting link_mtu to 1627
Wed May 19 11:13:57 2021 OPTIONS IMPORT: peer-id set
Wed May 19 11:13:57 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed May 19 11:13:57 2021 OPTIONS IMPORT: route options modified
Wed May 19 11:13:57 2021 OPTIONS IMPORT: --ifconfig/up options modified
Wed May 19 11:13:57 2021 Socket flags: TCP_NODELAY=1 succeeded
Wed May 19 11:13:57 2021 OPTIONS IMPORT: --socket-flags option modified
Wed May 19 11:13:57 2021 Socket Buffers: R=[367360->425984] S=[87040->425984]
Wed May 19 11:13:57 2021 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Wed May 19 11:13:57 2021 OPTIONS IMPORT: compression parms modified
Wed May 19 11:13:57 2021 OPTIONS IMPORT: timers and/or timeouts modified
Wed May 19 11:13:57 2021 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.10.100.1,sndbuf 524288,rcvbuf 524288,comp-lzo no,route 10.10.128.1,topology net30,ping 60,ping-restart 120,socket-flags TCP_NODELAY,ifconfig 10.10.128.6 10.10.128.5,peer-id 0,cipher AES-128-GCM'
Wed May 19 11:13:57 2021 SENT CONTROL [uk5-4096]: 'PUSH_REQUEST' (status=1)
Wed May 19 11:13:56 2021 [uk5-4096] Peer Connection Initiated with [AF_INET]xxxxxxx:26000
Wed May 19 11:13:56 2021 Control Channel: TLSv1.2, cipher TLSv1.2 DHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Wed May 19 11:13:55 2021 VERIFY OK: depth=0, CN=uk5-4096
Wed May 19 11:13:55 2021 VERIFY EKU OK
Wed May 19 11:13:55 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed May 19 11:13:55 2021 Validating certificate extended key usage
Wed May 19 11:13:55 2021 VERIFY KU OK
Wed May 19 11:13:55 2021 VERIFY OK: depth=1, C=RO, ST=BUC, O=VPN.AC, OU=VPN.AC CA, CN=VPN.AC, emailAddress=info@vpn.ac
Wed May 19 11:13:55 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed May 19 11:13:55 2021 TLS: Initial packet from [AF_INET]xxxxxxxx:26000, sid=09bab6aa 06a52d03
Wed May 19 11:13:55 2021 TCP_CLIENT link remote: [AF_INET]xxxxxxx:26000
Wed May 19 11:13:55 2021 TCP_CLIENT link local: (not bound)
Wed May 19 11:13:55 2021 TCP connection established with [AF_INET]xxxxxx:26000
Wed May 19 11:13:54 2021 Attempting to establish TCP connection with [AF_INET]xxxxx:26000 [nonblock]
Wed May 19 11:13:54 2021 Socket Buffers: R=[87380->87380] S=[16384->16384]
Wed May 19 11:13:54 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]xxxxxxx:26000
Wed May 19 11:13:54 2021 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed May 19 11:13:54 2021 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed May 19 11:13:54 2021 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed May 19 11:13:54 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed May 19 11:13:54 2021 WARNING: file 'credentials.conf' is group or others accessible
2021-05-19 11:13:53.955922 [INFO] Starting OpenVPN...
2021-05-19 11:13:53.894630 [INFO] Adding 1.0.0.1 to resolv.conf
2021-05-19 11:13:53.831722 [INFO] Adding 1.1.1.1 to resolv.conf
2021-05-19 11:13:53.696596 [INFO] VPN_OPTIONS not defined (via -e VPN_OPTIONS)
2021-05-19 11:13:53.633324 [INFO] NAME_SERVERS defined as '1.1.1.1,1.0.0.1'
2021-05-19 11:13:53.573938 [INFO] LAN_NETWORK defined as '192.168.10.0/24,10.8.0.0/29'
2021-05-19 11:13:53.511454 [INFO] VPN_DEVICE_TYPE defined as 'tun0'
2021-05-19 11:13:53.449651 [INFO] VPN_PROTOCOL defined as 'tcp-client'
2021-05-19 11:13:53.384433 [INFO] VPN_PORT defined as '12200'
2021-05-19 11:13:53.322264 [INFO] VPN_REMOTE defined as ‘xxxxxxxx’
2021-05-19 11:13:53.261399 [INFO] VPN remote line defined as ‘xxxxxxx 12200'
dos2unix: converting file /config/openvpn/xxxxxxxxx.ovpn to Unix format...
2021-05-19 11:13:52.988474 [INFO] OpenVPN config file is found at /config/openvpn/xxxxxxx.ovpn
2021-05-19 11:13:52.716332 [INFO] VPN_TYPE defined as 'openvpn'
2021-05-19 11:13:52.627581 [INFO] VPN_ENABLED defined as 'yes'

**Comment by rprice2021** [comment]
OK.  The problem was a fat-fingered leading space in VPN_PASSWORD.  Apologies.
Once I removed that the container starts up as expected and launches nzbget etc.
However, when I try to connect to the nzbget webui the browser session hangs and eventually I get a 'server dropped the connection' message.
The log is pasted below - there are some iptables error messages which may be relevant?
Thanks for the help?

2021-05-19 11:14:04.835023 [INFO] Network is up
2021-05-19 11:14:04.552488 [INFO] Started NZBGet daemon successfully...
2021-05-19 11:14:04.454258 [INFO] NZBGet PID: 237
Logging to /config/NZBGet/logs/nzbget.log.
2021-05-19 11:14:03.320698 [INFO] Starting NZBGet daemon...
req: No value provided for Subject Attribute CN, skipped
req: No value provided for Subject Attribute OU, skipped
req: No value provided for Subject Attribute O, skipped
-----
writing new private key to '/config/NZBGet/WebUIKey.key'
.......................+++++
.............................+++++
Generating a RSA private key
2021-05-19 11:14:02.866895 [WARNING] WebUI Key is missing, generating a new Certificate and Key
Wed May 19 11:14:02 2021 Initialization Sequence Completed
Wed May 19 11:14:02 2021 /sbin/ip route add 10.10.128.1/32 via 10.10.128.5
Wed May 19 11:14:02 2021 /sbin/ip route add 128.0.0.0/1 via 10.10.128.5
Wed May 19 11:14:02 2021 /sbin/ip route add 0.0.0.0/1 via 10.10.128.5
Wed May 19 11:14:02 2021 /sbin/ip route add xxxxxxxxx/32 via 172.17.0.1
2021-05-19 11:14:02.755444 [INFO] ENABLE_SSL is set to yes
2021-05-19 11:14:02.454972 [INFO] UMASK defined as '002'
2021-05-19 11:14:02.378234 [INFO] An user with PUID 1032 already exists in /etc/passwd, nothing to do.
2021-05-19 11:14:02.315771 [INFO] A group with PGID 100 already exists in /etc/group, nothing to do.
2021-05-19 11:14:02.255268 [INFO] Python3 is already installed, nothing to do.
--------------------
iptables/1.8.2 Failed to initialize nft: Protocol not supported
--------------------
2021-05-19 11:14:02.156693 [INFO] iptables defined as follows...
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
2021-05-19 11:14:00.745838 [INFO] iptable_mangle support detected, adding fwmark for tables
x_tables               16302  23 ip6table_filter,xt_ipvs,xt_iprange,xt_mark,ip6table_mangle,xt_recent,ip_tables,xt_tcpudp,ipt_MASQUERADE,xt_geoip,xt_limit,xt_state,xt_conntrack,xt_LOG,xt_mac,xt_nat,xt_multiport,iptable_filter,xt_TCPMSS,xt_REDIRECT,iptable_mangle,ip6_tables,xt_addrtype
ip_tables              14092  3 iptable_filter,iptable_mangle,iptable_nat
iptable_mangle          1656  0
--------------------
192.168.10.0/24 via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2 
10.10.128.5 dev tun0 proto kernel scope link src 10.10.128.6 
10.8.0.0/29 via 172.17.0.1 dev eth0 
default via 172.17.0.1 dev eth0 
--------------------
2021-05-19 11:14:00.649151 [INFO] ip route defined as follows...
2021-05-19 11:14:00.577925 [INFO] Adding 10.8.0.0/29 as route via docker eth0
2021-05-19 11:14:00.497333 [INFO] Adding 192.168.10.0/24 as route via docker eth0
2021-05-19 11:14:00.409973 [INFO] Docker network defined as 172.17.0.0/16
Wed May 19 11:13:59 2021 /sbin/ip addr add dev tun0 local 10.10.128.6 peer 10.10.128.5
Wed May 19 11:13:57 2021 /sbin/ip link set dev tun0 up mtu 1500
Wed May 19 11:13:57 2021 TUN/TAP TX queue length set to 100
Wed May 19 11:13:57 2021 TUN/TAP device tun0 opened
Wed May 19 11:13:57 2021 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Wed May 19 11:13:57 2021 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Wed May 19 11:13:57 2021 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Wed May 19 11:13:57 2021 Data Channel: using negotiated cipher 'AES-128-GCM'
Wed May 19 11:13:57 2021 OPTIONS IMPORT: data channel crypto options modified
Wed May 19 11:13:57 2021 OPTIONS IMPORT: adjusting link_mtu to 1627
Wed May 19 11:13:57 2021 OPTIONS IMPORT: peer-id set
Wed May 19 11:13:57 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed May 19 11:13:57 2021 OPTIONS IMPORT: route options modified
Wed May 19 11:13:57 2021 OPTIONS IMPORT: --ifconfig/up options modified
Wed May 19 11:13:57 2021 Socket flags: TCP_NODELAY=1 succeeded
Wed May 19 11:13:57 2021 OPTIONS IMPORT: --socket-flags option modified
Wed May 19 11:13:57 2021 Socket Buffers: R=[367360->425984] S=[87040->425984]
Wed May 19 11:13:57 2021 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Wed May 19 11:13:57 2021 OPTIONS IMPORT: compression parms modified
Wed May 19 11:13:57 2021 OPTIONS IMPORT: timers and/or timeouts modified
Wed May 19 11:13:57 2021 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.10.100.1,sndbuf 524288,rcvbuf 524288,comp-lzo no,route 10.10.128.1,topology net30,ping 60,ping-restart 120,socket-flags TCP_NODELAY,ifconfig 10.10.128.6 10.10.128.5,peer-id 0,cipher AES-128-GCM'
Wed May 19 11:13:57 2021 SENT CONTROL [uk5-4096]: 'PUSH_REQUEST' (status=1)
Wed May 19 11:13:56 2021 [uk5-4096] Peer Connection Initiated with [AF_INET]xxxxxxx:26000
Wed May 19 11:13:56 2021 Control Channel: TLSv1.2, cipher TLSv1.2 DHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Wed May 19 11:13:55 2021 VERIFY OK: depth=0, CN=uk5-4096
Wed May 19 11:13:55 2021 VERIFY EKU OK
Wed May 19 11:13:55 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed May 19 11:13:55 2021 Validating certificate extended key usage
Wed May 19 11:13:55 2021 VERIFY KU OK
Wed May 19 11:13:55 2021 VERIFY OK: depth=1, C=RO, ST=BUC, O=VPN.AC, OU=VPN.AC CA, CN=VPN.AC, emailAddress=info@vpn.ac
Wed May 19 11:13:55 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed May 19 11:13:55 2021 TLS: Initial packet from [AF_INET]xxxxxxxx:26000, sid=09bab6aa 06a52d03
Wed May 19 11:13:55 2021 TCP_CLIENT link remote: [AF_INET]xxxxxxx:26000
Wed May 19 11:13:55 2021 TCP_CLIENT link local: (not bound)
Wed May 19 11:13:55 2021 TCP connection established with [AF_INET]xxxxxx:26000
Wed May 19 11:13:54 2021 Attempting to establish TCP connection with [AF_INET]xxxxx:26000 [nonblock]
Wed May 19 11:13:54 2021 Socket Buffers: R=[87380->87380] S=[16384->16384]
Wed May 19 11:13:54 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]xxxxxxx:26000
Wed May 19 11:13:54 2021 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed May 19 11:13:54 2021 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed May 19 11:13:54 2021 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed May 19 11:13:54 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed May 19 11:13:54 2021 WARNING: file 'credentials.conf' is group or others accessible
2021-05-19 11:13:53.955922 [INFO] Starting OpenVPN...
2021-05-19 11:13:53.894630 [INFO] Adding 1.0.0.1 to resolv.conf
2021-05-19 11:13:53.831722 [INFO] Adding 1.1.1.1 to resolv.conf
2021-05-19 11:13:53.696596 [INFO] VPN_OPTIONS not defined (via -e VPN_OPTIONS)
2021-05-19 11:13:53.633324 [INFO] NAME_SERVERS defined as '1.1.1.1,1.0.0.1'
2021-05-19 11:13:53.573938 [INFO] LAN_NETWORK defined as '192.168.10.0/24,10.8.0.0/29'
2021-05-19 11:13:53.511454 [INFO] VPN_DEVICE_TYPE defined as 'tun0'
2021-05-19 11:13:53.449651 [INFO] VPN_PROTOCOL defined as 'tcp-client'
2021-05-19 11:13:53.384433 [INFO] VPN_PORT defined as '12200'
2021-05-19 11:13:53.322264 [INFO] VPN_REMOTE defined as ‘xxxxxxxx’
2021-05-19 11:13:53.261399 [INFO] VPN remote line defined as ‘xxxxxxx 12200'
dos2unix: converting file /config/openvpn/xxxxxxxxx.ovpn to Unix format...
2021-05-19 11:13:52.988474 [INFO] OpenVPN config file is found at /config/openvpn/xxxxxxx.ovpn
2021-05-19 11:13:52.716332 [INFO] VPN_TYPE defined as 'openvpn'
2021-05-19 11:13:52.627581 [INFO] VPN_ENABLED defined as 'yes'

**Comment by rprice2021** [comment]
All sorted.  Thanks.  There was a leading space in the VPN_PASSWORD field which was the culprit, but I had to rebuild from scratch to get it working.
